services:
  - type: web
    name: n8n-squoosh
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: your-username
      - key: N8N_BASIC_AUTH_PASSWORD
        value: your-password
      - key: WEBHOOK_TUNNEL_URL
        value: https://your-subdomain.onrender.com
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: NODE_ENV
        value: production
